<?php
global $SESSION, $USER_TYPES;

$STAFF = array(
    [
        "text" => "Home",
        "path" => '/',
        "icon" => '<i data-feather="home"></i>'
    ],
      [
        "text" => "Patients",
        "path" => '/patients',
        "icon" => '<i data-feather="user"></i>',
        "sub-content" => [
            [
                "text" => "Search Patients",
                "path" => '/patients/search_patients',
                "icon" => '<i data-feather="search"></i>'
            ],
            [
                "text" => "Evaluations",
                "path" => '/patients/evaluations',
                "icon" => '<i data-feather="clipboard"></i>'
            ],
            [
                "text" => "Color Vision Eval",
                "path" => '/patients/color_vision_evaluations',
                "icon" => '<i data-feather="eye"></i>'
            ],
            [
                "text" => "Dry Eyes Eval",
                "path" => '/patients/dry_eyes_evaluations',
                "icon" => '<i data-feather="droplet"></i>'
            ],
        ]
    ],
    [
        "text" => "Point of Sales",
        "path" => '/pos',
        "icon" => '<i data-feather="dollar-sign"></i>',
        "sub-content" => [
            [
                "text" => "Point of Sales",
                "path" => '/pos/point_of_sales',
                "icon" => '<i data-feather="credit-card"></i>'
            ],
            [
                "text" => "Orders",
                "path" => '/pos/orders',
                "icon" => '<i data-feather="shopping-cart"></i>'
            ],
            [
                "text" => "Lab Orders",
                "path" => '/pos/lab_orders',
                "icon" => '<i data-feather="flask"></i>'
            ],
            [
                "text" => "Delivery",
                "path" => '/pos/order_delivery',
                "icon" => '<i data-feather="truck"></i>'
            ],
            [
                "text" => "Payments",
                "path" => '/pos/payments',
                "icon" => '<i data-feather="credit-card"></i>'
            ],
        ]
    ],
    [
        "text" => "Inventory",
        "path" => '/inventory',
        "icon" => '<i data-feather="package"></i>',
        "sub-content" => [
            [
                "text" => "Products",
                "path" => '/inventory/products',
                "icon" => '<i data-feather="box"></i>'
            ],
            [
                "text" => "Packages",
                "path" => '/inventory/packages',
                "icon" => '<i data-feather="package"></i>'
            ],
            [
                "text" => "Product Types",
                "path" => '/inventory/product_types',
                "icon" => '<i data-feather="tag"></i>'
            ],
            [
                "text" => "Suppliers",
                "path" => '/inventory/suppliers',
                "icon" => '<i data-feather="truck"></i>'
            ],
            [
                "text" => "Categories",
                "path" => '/inventory/categories',
                "icon" => '<i data-feather="folder"></i>'
            ],
        ]
    ],
    [
        "text" => "Schedule",
        "path" => '/services/schedule',
        "icon" => '<i data-feather="calendar"></i>'
    ],
);

$ADMIN = array(
    [
        "text" => "Dashboard",
        "path" => '/',
        "icon" => '<i data-feather="activity"></i>'
    ],
    [
        "text" => "News Feed",
        "path" => '/newsfeed',
        "icon" => '<i data-feather="rss"></i>'
    ],
    [
        "text" => "Students",
        "path" => '/students',
        "icon" => '<i data-feather="users"></i>',
        "sub-content" => [
            [
                "text" => "Search Students",
                "path" => '/patients/search_students',
                "icon" => '<i data-feather="search"></i>'
            ],
            [
                "text" => "Classrooms",
                "path" => '/patients/classrooms',
                "icon" => '<i data-feather="layout"></i>'
            ],
            [
                "text" => "Groups",
                "path" => '/patients/groups',
                "icon" => '<i data-feather="users"></i>'
            ],
        ]
    ],
    [
        "text" => "Faculty Management",
        "path" => '/pos',
        "icon" => '<i data-feather="briefcase"></i>',
        "sub-content" => [
            [
                "text" => "Point of Sales",
                "path" => '/pos/point_of_sales',
                "icon" => '<i data-feather="dollar-sign"></i>'
            ],
            [
                "text" => "Orders",
                "path" => '/pos/orders',
                "icon" => '<i data-feather="shopping-cart"></i>'
            ],
            [
                "text" => "Lab Orders",
                "path" => '/pos/lab_orders',
                "icon" => '<i data-feather="flask"></i>'
            ],
            [
                "text" => "Delivery",
                "path" => '/pos/order_delivery',
                "icon" => '<i data-feather="truck"></i>'
            ],
            [
                "text" => "Payments",
                "path" => '/pos/payments',
                "icon" => '<i data-feather="credit-card"></i>'
            ],
            [
                "text" => "Reports",
                "path" => '/pos/reports',
                "icon" => '<i data-feather="bar-chart-2"></i>'
            ],
        ]
    ],
    [
        "text" => "Resources",
        "path" => '/resources',
        "icon" => '<i data-feather="book"></i>',
        "sub-content" => [
            [
                "text" => "Slot 1",
                "path" => '/inventory/products',
                "icon" => '<i data-feather="box"></i>'
            ],
            [
                "text" => "Slot 2",
                "path" => '/inventory/products',
                "icon" => '<i data-feather="box"></i>'
            ],
        ]
    ],
    [
        "text" => "Maintenance",
        "path" => '/maintenance',
        "icon" => '<i data-feather="tool"></i>',
        "sub-content" => [
            [
                "text" => "Courses",
                "path" => '/maintenance/courses',
                "icon" => '<i data-feather="book-open"></i>'
            ],
            [
                "text" => "Semesters",
                "path" => '/maintenance/semesters',
                "icon" => '<i data-feather="calendar"></i>'
            ],
            [
                "text" => "Classrooms",
                "path" => '/maintenance/classrooms',
                "icon" => '<i data-feather="layout"></i>'
            ],
            [
                "text" => "Slot 1",
                "path" => '/maintenance/slot1',
                "icon" => '<i data-feather="settings"></i>'
            ],
            [
                "text" => "Slot 1",
                "path" => '/maintenance/slot2',
                "icon" => '<i data-feather="settings"></i>'
            ],
        ]
    ],
    [
        "text" => "Accounts",
        "path" => '/accounts',
        "icon" => '<i data-feather="users"></i>',
        "sub-content" => [
            [
                "text" => "Students",
                "path" => '/accounts/students',
                "icon" => '<i data-feather="user"></i>'
            ],
            [
                "text" => "Faculty Members",
                "path" => '/accounts/faculty_members',
                "icon" => '<i data-feather="user-check"></i>'
            ]
        ]
    ],
);

$STUDENT = array(
    [
        "text" => "Dashboard",
        "path" => '/',
        "icon" => '<i data-feather="activity"></i>'
    ],
    [
        "text" => "News Feed",
        "path" => '/newsfeed',
        "icon" => '<i data-feather="rss"></i>'
    ],
    [
        "text" => "My Subjects",
        "path" => '/me/subjects',
        "icon" => '<i data-feather="book"></i>'
    ],
    [
        "text" => "My Section",
        "path" => '/me/section',
        "icon" => '<i data-feather="users"></i>'
    ],
    [
        "text" => "Resources",
        "path" => '/resources',
        "icon" => '<i data-feather="folder"></i>',
        "sub-content" => [
            [
                "text" => "Slot 1",
                "path" => '/inventory/slot1',
                "icon" => '<i data-feather="file"></i>'
            ],
            [
                "text" => "Slot 2",
                "path" => '/inventory/slot2',
                "icon" => '<i data-feather="file"></i>'
            ],
        ]
    ],
    [
        "text" => "Events & Announcements",
        "path" => '/maintenance',
        "icon" => '<i data-feather="bell"></i>',
        "sub-content" => [
            [
                "text" => "Events",
                "path" => '/maintenance/events',
                "icon" => '<i data-feather="calendar"></i>'
            ],
            [
                "text" => "Slot 1",
                "path" => '/maintenance/slot1',
                "icon" => '<i data-feather="info"></i>'
            ],
            [
                "text" => "Slot 1",
                "path" => '/maintenance/slot2',
                "icon" => '<i data-feather="info"></i>'
            ],
        ]
    ],
);

$isProfessor =  $SESSION->user_type == 2 && !empty($SESSION->getAsProfessor());

$FACULTY = array(
    [
        "text" => "Dashboard",
        "path" => '/',
        "icon" => '<i data-feather="activity"></i>'
    ],
    [
        "text" => "News Feed",
        "path" => '/newsfeed',
        "icon" => '<i data-feather="rss"></i>'
    ],
    ($isProfessor ? [
        "text" => "My Classes",
        "path" => '/me/classes',
        "icon" => '<i data-feather="layout"></i>'
    ]: []),
    [
        "text" => "Students",
        "path" => '/students',
        "icon" => '<i data-feather="users"></i>',
        "sub-content" => [
            [
                "text" => "Students",
                "path" => '/students/students',
                "icon" => '<i data-feather="users"></i>'
            ],
            [
                "text" => "Search Students",
                "path" => '/students/search_students',
                "icon" => '<i data-feather="search"></i>'
            ],
        ]
    ],
    [
        "text" => "Events & Announcements",
        "path" => '/maintenance',
        "icon" => '<i data-feather="bell"></i>',
        "sub-content" => [
            [
                "text" => "Events",
                "path" => '/maintenance/events',
                "icon" => '<i data-feather="calendar"></i>'
            ],
            [
                "text" => "Slot 1",
                "path" => '/maintenance/slot1',
                "icon" => '<i data-feather="info"></i>'
            ],
            [
                "text" => "Slot 1",
                "path" => '/maintenance/slot2',
                "icon" => '<i data-feather="info"></i>'
            ],
        ]
    ],
);

$SUPERADMIN = array(
    [
        "text" => "Dashboard",
        "path" => '/',
        "icon" => '<i data-feather="activity"></i>'
    ],
    [
        "text" => "News Feed",
        "path" => '/newsfeed',
        "icon" => '<i data-feather="rss"></i>'
    ],
    [
        "text" => "Students",
        "path" => '/students',
        "icon" => '<i data-feather="users"></i>',
        "sub-content" => [
            [
                "text" => "Students",
                "path" => '/students/students',
                "icon" => '<i data-feather="users"></i>'
            ],
            [
                "text" => "Import Students",
                "path" => '/students/import_students',
                "icon" => '<i data-feather="upload"></i>'
            ],
            [
                "text" => "Search Students",
                "path" => '/students/search_students',
                "icon" => '<i data-feather="search"></i>'
            ],
        ]
    ],
    [
        "text" => "Faculty Management",
        "path" => '/faculty',
        "icon" => '<i data-feather="briefcase"></i>',
        "sub-content" => [
            [
                "text" => "Professors",
                "path" => '/faculty/professors',
                "icon" => '<i data-feather="user-check"></i>'
            ],
            [
                "text" => "Staffs",
                "path" => '/faculty/staffs',
                "icon" => '<i data-feather="user"></i>'
            ],
        ]
    ],
    [
        "text" => "Resources",
        "path" => '/resources',
        "icon" => '<i data-feather="folder"></i>',
        "sub-content" => [
            [
                "text" => "Slot 1",
                "path" => '/inventory/products',
                "icon" => '<i data-feather="file"></i>'
            ],
            [
                "text" => "Slot 2",
                "path" => '/inventory/products',
                "icon" => '<i data-feather="file"></i>'
            ],
        ]
    ],
    [
        "text" => "Maintenance",
        "path" => '/maintenance',
        "icon" => '<i data-feather="tool"></i>',
        "sub-content" => [
            [
                "text" => "Sections",
                "path" => '/maintenance/sections',
                "icon" => '<i data-feather="grid"></i>'
            ],
            [
                "text" => "Courses",
                "path" => '/maintenance/courses',
                "icon" => '<i data-feather="book-open"></i>'
            ],
            [
                "text" => "Subjects",
                "path" => '/maintenance/subjects',
                "icon" => '<i data-feather="book"></i>'
            ],
            [
                "text" => "Classrooms",
                "path" => '/maintenance/classrooms',
                "icon" => '<i data-feather="layout"></i>'
            ],
            [
                "text" => "Year Levels",
                "path" => '/maintenance/year_levels',
                "icon" => '<i data-feather="layers"></i>'
            ],
            [
                "text" => "Departments",
                "path" => '/maintenance/departments',
                "icon" => '<i data-feather="briefcase"></i>'
            ],
            [
                "text" => "Semesters",
                "path" => '/maintenance/semesters',
                "icon" => '<i data-feather="calendar"></i>'
            ],
            [
                "text" => "Events",
                "path" => '/maintenance/events',
                "icon" => '<i data-feather="calendar"></i>'
            ],
            [
                "text" => "Slot 1",
                "path" => '/maintenance/slot1',
                "icon" => '<i data-feather="info"></i>'
            ],
            [
                "text" => "Slot 2",
                "path" => '/maintenance/slot2',
                "icon" => '<i data-feather="info"></i>'
            ],
        ]
    ],
    [
        "text" => "Accounts",
        "path" => '/accounts',
        "icon" => '<i data-feather="users"></i>',
        "sub-content" => [
            [
                "text" => "Students",
                "path" => '/accounts/students',
                "icon" => '<i data-feather="user"></i>'
            ],
            [
                "text" => "Faculty Members",
                "path" => '/accounts/faculty_members',
                "icon" => '<i data-feather="user-check"></i>'
            ],
            [
                "text" => "Administrators",
                "path" => '/accounts/administrators',
                "icon" => '<i data-feather="user-plus"></i>'
            ],
        ]
    ],
);

$ALL = [$STUDENT, $FACULTY, $ADMIN, $SUPERADMIN];
$NAVLINKS = $ALL[$SESSION->user_type - 1];

?>


<nav class="main-navbar" data-session-id="<?= $SESSION->user_id ?>" data-session-type="<?= $SESSION->user_type ?>">
<!--    <div class="nav-header">-->

    <!-- Feather Icons CDN for thin icons -->
   


<!--    </div>-->
    <div class="nav-body">
        <div class="nav-link-items">
            <?php foreach ($NAVLINKS as $link): ?>
                <?php if(!empty($link)): ?>
            <?php
            if ($this->view_path === "/") {
                $match = $this->view_path === $link['path'];
            } else {
                $match = '/' . $this->view_path === $link['path'];
            }
            ?>
            <?php if (isset($link['sub-content'])): ?>
            <a>
                <?php else: ?>
                    <a href="<?= $link['path'] ?>">
                        <?php endif; ?>
                        <div class="nav-link <?= $match ? 'active' : '' ?>" data-path="<?= $link['path'] ?>">
                            <div class="main">
                                <div class="icon">
                                    <?= $link['icon'] ?? '' ?>
                                </div>
                                <div class="text">
                                    <span>
                                        <?= $link['text'] ?>
                                    </span>
                                </div>
                            </div>
                            <?php if (isset($link['sub-content'])): ?>
                                <div class="sub-content" data-path="<?= $link['path'] ?>">
                                    <?php foreach ($link['sub-content'] as $item): ?>
                                        <?php
                                        if ($this->view_path === "/") {
                                            $match = $this->view_path === $item['path'];
                                        } else {
                                            $match = '/' . $this->view_path === $item['path'];
                                        }
                                        ?>
                                        <a href="<?= $item['path'] ?>">
                                            <div class="sub-link <?= $match ? 'active' : '' ?>">
                                                <div class="icon">
                                                    <?= $item['icon'] ?? '' ?>
                                                </div>
                                                <div class="text">
                                                <span>
                                                    <?= $item['text'] ?>
                                                </span>
                                                </div>
                                            </div>
                                        </a>
                                    <?php endforeach ?>
                                </div>
                            <?php endif ?>
                        </div>
                    </a>
                <?php endif ?>
            <?php
            endforeach; ?>
        </div>
    </div>
</nav>