<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- <link rel="stylesheet" href="/public/assets/styles/css/styles.css"> -->
    <link rel="stylesheet" href="/public/assets/styles/sass/styles.css">
    <link rel="icon" href="/public/assets/media/ui/logo.png"/>

    <script src="https://unpkg.com/feather-icons"></script>
    <!-- <script src="/public/assets/scripts/libraries/jszip.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
