<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$courseControl = $APPLICATION->FUNCTIONS->STAFF_CONTROL;

$data = json_decode($_POST['data'], true);

$staff = $courseControl->get($data['id'], true);

$courses = $APPLICATION->FUNCTIONS->DEPARTMENT_CONTROL->getAllRecords(false);

$courses = ObjectToCombo("department_name", "department_id", $courses);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Staff</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Select Faculty Member</span>
                            </div>
                            <div class="error-container">
                                <input type="text" name="user_id" placeholder="Select Faculty Member" readonly value="<?= $staff->user->displayName ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Department</span>
                            </div>
                            <label for=""><span>Department</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("department_id", "Department", $courses, false, [
                                        'text' => $staff->department->department_name,
                                        'value' => $staff->department_id
                                ]) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description</span>
                            </div>
                            <label for=""><span>Description</span></label>

                            <div class="error-container">
                                <textarea name="description" placeholder="Description" cols="30" rows="10"><?= $staff->description ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>