<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$section_id = $data['section_id'];

$sectionSubjectControl = $APPLICATION->FUNCTIONS->SECTION_SUBJECT_CONTROL;
$groupControl = $APPLICATION->FUNCTIONS->RESOURCES_GROUP_CONTROL;

$groups = [
    [
        "resources_group_id" => 0,
        "title" => "Create New Group"
    ]
];

$groups = array_merge($groups, $groupControl->filterRecords(['section_id' => $section_id], false));

$subjects = $sectionSubjectControl->filterRecords(['section_id' => $section_id], true);
$subjects = array_map(function($subject) {
    return [
        "section_subject_id" => $subject->section_subject_id,
        "subject_name" => $subject->subject->subject_name
    ];
}, $subjects);

$groups = ObjectToCombo("title", "resources_group_id", $groups);
$subjects = ObjectToCombo("subject_name", "section_subject_id", $subjects);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Resource</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control" enctype="multipart/form-data">
                <div class="popup-bot">
                   
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text" name="title" placeholder="Title">
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description</span>
                            </div>
                            <label for=""><span>Description</span></label>

                            <div class="error-container">
                                <textarea name="description" placeholder="Description" cols="30" rows="10"></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Upload File</span>
                            </div>
                            <label for=""><span>Upload File</span></label>

                            <div class="error-container">
                                <input type="file" name="file" placeholder="Upload File">
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Subject</span>
                            </div>
                            <label for=""><span>Subject</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("section_subject_id", "Subject", $subjects) ?>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Upload to Group (Optional)</span>
                            </div>
                            <label for=""><span>Upload to Group (Optional)</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("group_id", "Upload to Group (Optional)", $groups) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group flex">
                        <div class="form-group filled-green">
                            <div class="text-button">
                                <div class="text">
                                    <span>New Resource</span>
                                </div>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>