<?php

global $APPLICATION, $COURSE_HEADER_BODY, $SESSION;

$student = $SESSION->getAsStudent();;

$sectionStudent = $student->getSectionStudent();

$section = $sectionStudent->section;

$subjects = $section->subjects;

?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Subjects</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

</div>

<div class="right-content">

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Subjects</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body">
                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>List of Subjects</h2>
                                    </div>
                                </div>
                                <div class="center">
                                    <div class="search-engine-parent full-width">
                                        <div class="search-engine">
                                            <div class="icon">
                                                <?= UseIcon("magnifying-glass-thin") ?>
                                            </div>
                                            <input type="text" name="search-records" placeholder="Search Records...">
                                        </div>
                                    </div>
                                </div>
                                <div class="right"></div>
                            </div>
                        </div>
                        <div class="main-table-body main-table-requests" >
<!--                                --><?php
//                                var_dump($subjects);
//                                ?>

                            <div class="cards-flex-container">
                                <?php foreach ($subjects as $subject): ?>
                                    <div class="card-flex-container">
                                        <div class="title">
                                            <h2><?= $subject->subject->subject_name ?></h2>
                                            <p><?= $subject->professor->displayName ?></p>
                                            <small><?= $subject->schedule->schedule_label ?></small>
                                        </div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/student/me/subjects.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
