<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;



?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Event</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Event Title</span>
                            </div>
                            <label for=""><span>Event Title</span></label>
                            <div class="error-container">
                                <input type="text" name="title" placeholder="Event Title" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description</span>
                            </div>
                            <label for=""><span>Event Description</span></label>

                            <div class="error-container">
                                <div class="creator-textarea">
                                    <textarea name="description" id="editor" placeholder="What's on your mind, <?= $SESSION->displayName ?>">
                                    </textarea>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Date Start</span>
                            </div>
                            <label for=""><span>Date Start</span></label>

                            <div class="error-container">
                                <input type="date" name="date_start" placeholder="Date Start">
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Date End</span>
                            </div>
                            <label for=""><span>Date End</span></label>

                            <div class="error-container">
                                <input type="date" name="date_end" placeholder="Date End">
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Poster</span>
                            </div>
                            <label for=""><span>Poster</span></label>

                            <div class="error-container">
                                <input type="file" name="poster" placeholder="Poster">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>