<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;



?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content post-creator-popup">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Post</h1>
                </div>
                <div class="paragraph">
                    <p>Create new Post</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control main-creator">
                <div class="post-content">
                    <div class="creator-textarea">
                        <textarea name="content" id="editor" placeholder="What's on your mind, <?= $SESSION->displayName ?>">
                        </textarea>
                    </div>
                    <section class="splide post-gallery" aria-labelledby="carousel-heading">
                        <div class="splide__track">
                            <ul class="splide__list">
                            </ul>
                        </div>
                    </section>
                    <div class="creator-upload">
                        <div id="drop_zone">
                            <p>Drag your Images in this <i>drop zone</i>.</p>
                        </div>
                    </div>

                    <div class="form-group-container flex other-content">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Post Type</span>
                            </div>
                            <label for=""><span>Post Type</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("post_type", "Post Type", CasesToCombo(PostTypes::cases())) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group filled-green">
                            <input type="submit" value="Post">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>