<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$control = $APPLICATION->FUNCTIONS->PROFESSOR_CONTROL;

$data = json_decode($_POST['data'], true);

$professor = $control->get($data['id'], true);

$courseControl = $APPLICATION->FUNCTIONS->COURSE_CONTROL;

$courses = $courseControl->getAllRecords(false);

$courses = ObjectToCombo("course_name", "course_id", $courses);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Professor</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Select Faculty Member</span>
                            </div>
                            <div class="error-container">
                                <div class="custom-select-box select-faculty">
                                    <div class="main-content">
                                        <input type="text" name="user_id" placeholder="Select Faculty Member" readonly value="<?= $professor->user_id ?>">

                                        <div class="icon">
                                            <svg width="256px" height="256px" viewBox="0 0 256 256" id="Flat" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M138.82861,130.82861l-80,80a4.00026,4.00026,0,0,1-5.65722-5.65722L130.34326,128,53.17139,50.82861a4.00026,4.00026,0,0,1,5.65722-5.65722l80,80A4.0006,4.0006,0,0,1,138.82861,130.82861Zm80-5.65722-80-80a4.00026,4.00026,0,0,0-5.65722,5.65722L210.34326,128l-77.17187,77.17139a4.00026,4.00026,0,0,0,5.65722,5.65722l80-80A4.0006,4.0006,0,0,0,218.82861,125.17139Z"/>
                                            </svg>

                                        </div>
                                    </div>
                                </div>
                                <!--                                <input type="text" name="employee" placeholder="Employee" >-->
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Main Course</span>
                            </div>
                            <label for=""><span>Main Course</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("main_course_id", "Main Course", $courses, false, ["text" => $professor->main_course_id, "value" => $professor->main_course_id]) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description</span>
                            </div>
                            <label for=""><span>Description</span></label>

                            <div class="error-container">
                                <textarea name="description" placeholder="Description" cols="30" rows="10"><?= $professor->description ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>