<?php

global $APPLICATION, $COURSE_HEADER_BODY;

$control = $APPLICATION->FUNCTIONS->COURSE_CONTROL;
$RECORDS = $control->getAllRecords(false);

?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Courses</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

</div>

<div class="right-content">

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Courses</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body">
                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>List of Courses</h2>
                                    </div>
                                </div>
                                <div class="center">
                                    <div class="search-engine-parent full-width">
                                        <div class="search-engine">
                                            <div class="icon">
                                                <?= UseIcon("magnifying-glass-thin") ?>
                                            </div>
                                            <input type="text" name="search-records" placeholder="Search Records...">
                                        </div>
                                    </div>
                                </div>
                                <div class="right"></div>
                            </div>
                            <div class="table-buttons">
                                <div class="left"></div>
                                <div class="right">
                                    <div class="icon-button table-button show-component" data-name="view-request">
                                        <div class="icon">
                                            <?= UseIcon("eye-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>View</span>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="delete-request">
                                        <div class="icon">
                                            <?= UseIcon("trash-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>Delete</span>
                                        </div>
                                    </div>

                                    <div class="icon-button table-button show-component" data-name="add-request">
                                        <div class="icon">
                                            <?= UseIcon("plus-thin") ?>
                                        </div>
                                        <div class="text">
                                            <span>New</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="main-table-body main-table-requests"  data-user-type="3">
                            <?= CreateTable([
                                "content" => $COURSE_HEADER_BODY,
                                "data" => $RECORDS,
                                "id" => "course_id"
                            ]) ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/superadmin/maintenance/courses.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
