<?php

global $APPLICATION, $USER_HEADER_BODY;

$control = $APPLICATION->FUNCTIONS->USER_CONTROL;
$RECORDS = $control->filterRecords(['user_type' => 3],true);

?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Year Levels</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

</div>

<div class="right-content">

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>All Year Levels</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body">
                <div class="data-bordered-container">
                    <div class="content">
                        <div class="content-as-list">
                            <div class="list-item-container">
                                <div class="left">
                                    <p>First Year</p>
                                    <small>Enable/Disable First Year</small>
                                </div>
                                <div class="right">
                                    <?= CreateSwitch([
                                        "name"  => "first_year_level",
                                        "value" => true
                                    ]) ?>
                                </div>
                            </div>
                            <div class="list-item-container">
                                <div class="left">
                                    <p>Second Year</p>
                                    <small>Enable/Disable Second Year</small>
                                </div>
                                <div class="right">
                                    <?= CreateSwitch([
                                        "name"  => "second_year_level",
                                        "value" => true
                                    ]) ?>
                                </div>
                            </div>
                            <div class="list-item-container">
                                <div class="left">
                                    <p>Third Year</p>
                                    <small>Enable/Disable Third Year</small>
                                </div>
                                <div class="right">
                                    <?= CreateSwitch([
                                        "name"  => "third_year_level",
                                        "value" => true
                                    ]) ?>
                                </div>
                            </div>
                            <div class="list-item-container">
                                <div class="left">
                                    <p>Fourth Year</p>
                                    <small>Enable/Disable Fourth Year</small>
                                </div>
                                <div class="right">
                                    <?= CreateSwitch([
                                        "name"  => "fourth_year_level",
                                        "value" => true
                                    ]) ?>
                                </div>
                            </div>
                            <div class="list-item-container">
                                <div class="left">
                                    <p>Create Year</p>
                                    <small>Add new year level</small>
                                </div>
                                <div class="right">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/superadmin/accounts/accounts.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
