<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$grading_platform_id = $data['grading_platform_id'];

$categories = [
    ["text" => "Activity", "value" => GradeScoreCategories::ACTIVITY->value],
    ["text" => "Exam", "value" => GradeScoreCategories::EXAM->value],
];
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>Import Grade Score </h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Category</span>
                            </div>
                            <label for=""><span>Category</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("category", "Category", $categories) ?>
                            </div>
                        </div>
                    </div>

                    <div class="data-main-content hide-component">
                        <div class="form-group-container flex">
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Select Data</span>
                                </div>
                                <label for=""><span>Select Data</span></label>

                                <div class="error-container">
                                    <?= CreateComboBox("data", "Select Data", []) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group filled-green">
                            <input type="submit" value="Import">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>