<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$grade_score = $APPLICATION->FUNCTIONS->GRADE_SCORE_CONTROL->get( $data['id'], false);

$complied = $APPLICATION->FUNCTIONS->ACTIVITY_COMPLY_CONTROL->get($grade_score['id'], false);

$activity = $APPLICATION->FUNCTIONS->ACTIVITY_CONTROL->get($complied['activity_id'], false);

?>  
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Grade Score</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text"  placeholder="Title" readonly value="<?= $activity['title'] ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Grade</span>
                            </div>
                            <label for=""><span>Grade</span></label>

                            <div class="error-container">
                                <input type="number" step="0.01" name="grade" placeholder="Grade" value="<?= $grade_score['grade'] ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                            <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>