<?php
 global $ADMIN_USER_TYPES;
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="/public/assets/styles/css/styles.css">

</head>
<body>
<div class="main-auth-container">
    <div class="auth-container-admin">
        <div class="auth-bot">
            <form action="" class="form-control">
                <div class="auth-header">
                    <div class="logo">
                        <img src="/public/assets/media/ui/logo.png" alt="">
                    </div>
                    <div class="main-header">
                        <h1>Welcome Administrator!</h1>
                        <p>Please login to your Account</p>
                    </div>
                </div>
                <div class="main-form">
                    <div class="main-content">
                        <div class="main-body">
                            <div class="form-group-container">
                                <div class="form-group">
                                    <input type="text" placeholder="Email" name="email">
                                </div>
                            </div>
                            <div class="form-group-container">
                                <div class="form-group">
                                    <input type="password" placeholder="Password" name="password">
                                </div>
                            </div>
                            <div class="form-group-container">
                                <div class="form-group">
                                    <?= CreateComboBox("user_type", "User Type", [
                                        ["text" => "Admin", "value" => 3],
                                        ["text" => "Super Admin", "value" => 4],
                                    ]) ?>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="link right">
                                    <a href=""><span>Forgot Password</span></a>
                                </div>
                            </div>

                            <div class="form-group-container submit-group">
                                <div class="form-group">
                                    <div class="submit-input" >
                                        <input type="submit" class="medium-width" value="SIGN IN">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<section id="big-pipes-container">
    <section id="system-messages"></section>
    <section id="system-notifications">
        <section id="system-notification"></section>
    </section>
    <section id="system-popup"></section>
</section>
</body>
<script type="module" src="/public/assets/scripts/auth/admin.js"> </script>

</html>