<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;


$data = json_decode($_POST['data'], true);

$sectionSubject = $APPLICATION->FUNCTIONS->SECTION_SUBJECT_CONTROL->get($data['id'], true);
$subjects = $APPLICATION->FUNCTIONS->SUBJECT_CONTROL->getAllRecords(false);

$subjects = ObjectToCombo("subject_name", "subject_id", $subjects);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Section Subject</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Subject</span>
                            </div>
                            <label for=""><span>Subject</span></label>

                            <div class="error-container">
                                <input type="text" placeholder="Subject" readonly value="<?= $sectionSubject->subject->subject_name ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Professor</span>
                                </div>
                                <label for=""><span>Professor</span></label>
                            <div class="error-container">
                                <input type="text" placeholder="Professor" readonly value="<?= $sectionSubject->professor->displayName ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="text-button add-schedule">
                                <div class="text">
                                    <span>ADD SCHEDULES</span>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>