<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$record = $APPLICATION->FUNCTIONS->DEPARTMENT_CONTROL->get($_POST['id'], true);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Department</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Department Name</span>
                            </div>
                            <label for=""><span>Department Name</span></label>
                            <div class="error-container">
                                <input type="text" name="department_name" placeholder="Department Name" value="<?= $record->department_name ?>">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Head</span>
                            </div>
                            <label for=""><span>Head</span></label>

                            <div class="error-container">
                                <input type="text" name="head" placeholder="Head"  value="<?= $record->head ?>">
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>