<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);
$user_type = $data['user_type'];

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New <?= $ALL_USER_TYPES[$user_type - 1] ?></h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Email Address</span>
                            </div>
                            <label for=""><span>Username</span></label>
                            <div class="error-container">
                                <input type="email" name="email" placeholder="Email Address" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Password</span>
                            </div>
                            <label for=""><span>Password</span></label>

                            <div class="error-container">
                                <input type="password" name="password" placeholder="Password">
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Firstname</span>
                            </div>
                            <label for=""><span>Firstname</span></label>
                            <div class="error-container">
                                <input type="text" name="firstname" placeholder="Firstname" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Lastname</span>
                            </div>
                            <label for=""><span>Lastname</span></label>
                            <div class="error-container">
                                <input type="text" name="lastname" placeholder="Lastname" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Birthdate</span>
                            </div>
                            <label for=""><span>Birthdate</span></label>
                            <div class="error-container">
                                <input type="date" name="birthdate" placeholder="Birthdate" >
                            </div>
                        </div>
                    </div>

                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>