<?php

global $APPLICATION, $COURSE_HEADER_BODY, $SESSION;

$professor = $SESSION->getAsProfessor();

$classes = $professor->getClasses();

$firstYears = array_filter($classes, function ($section) {
    return $section->year_level == 1;
});

$secondYears = array_filter($classes, function ($section) {
    return $section->year_level == 2;
});

$thirdYears = array_filter($classes, function ($section) {
    return $section->year_level == 3;
});

$fourthYears = array_filter($classes, function ($section) {
    return $section->year_level == 4;
});
?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Classes</title>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

</div>

<div class="right-content">

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Classes</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body">
                <div class="data-table-content">
                    <div class="main-table-container table-component">
                        <div class="main-table-header">
                            <div class="table-header">
                                <div class="left">
                                    <div class="title">
                                        <h2>List of Classes</h2>
                                    </div>
                                </div>
                                <div class="center">
                                    <div class="search-engine-parent full-width">
                                        <div class="search-engine">
                                            <div class="icon">
                                                <?= UseIcon("magnifying-glass-thin") ?>
                                            </div>
                                            <input type="text" name="search-records" placeholder="Search Records...">
                                        </div>
                                    </div>
                                </div>
                                <div class="right"></div>
                            </div>
                        </div>
                        <div class="main-table-body main-table-requests" >

                            <?php
                            $i = 1;
                            foreach ([$firstYears, $secondYears, $thirdYears, $fourthYears] as $year):?>
                                <?php if (count($year)): ?>
                                    <div class="cards-title">
                                        <div class="title">
                                            <h2><?= $i ?>st Year</h2>
                                        </div>
                                    </div>
                                    <div class="cards-flex-container">
                                        <?php foreach ($year as $section): ?>
                                            <?php
                                            $students = $section->getAllStudents();
                                            ?>
                                            <div class="card-flex-container">
                                                <div class="title">
                                                    <h2><?= $section->section_name ?></h2>
                                                    <p><?= count($students) ?> Students</p>
                                                    <small><?= count($section->subjects) ?> Subjects</small>
                                                </div>
                                            </div>
                                        <?php endforeach; ?>
                                    </div>
                            <?php endif ?>
                                <?php  $i++ ?>
                            <?php endforeach ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>

    <script type="module" src="/public/assets/scripts/pages/student/me/subjects.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
