<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$exam = $APPLICATION->FUNCTIONS->EXAM_CONTROL->get($data['id'], true);

$section_id = $exam->section_id;

$subjects = $APPLICATION->FUNCTIONS->SECTION_SUBJECT_CONTROL->filterRecords(['section_id' => $section_id], true);

$subjects = array_map(function($subject) {
    return [
        "section_subject_id" => $subject->section_subject_id,
        "subject_name" => $subject->subject->subject_name
    ];
}, $subjects);

$subjects = ObjectToCombo("subject_name", "section_subject_id", $subjects);

$is_editable = $SESSION->user_type == 2;
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Exam</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Subject</span>
                            </div>
                            <label for=""><span>Subject</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("section_subject_id", "Subject", $subjects, false, [
                                    "value" => $exam->section_subject_id,
                                    "text" => $exam->section_subject->subject->subject_name
                                ]) ?>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text" name="title" placeholder="Title" value="<?= $exam->title ?>" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Duration</span>
                            </div>
                            <label for=""><span>Duration</span></label>

                            <div class="error-container">
                                <input type="text" name="duration" placeholder="Duration" value="<?= $exam->duration ?>" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Count Items</span>
                            </div>
                            <label for=""><span>Count Items</span></label>

                            <div class="error-container">
                                <input type="number" name="count_items" placeholder="Count Items" value="<?= $exam->count_items ?>" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Date Start</span>
                            </div>
                            <label for=""><span>Date Start</span></label>
                            <div class="error-container">
                                <input type="datetime-local" name="date_start" placeholder="Date Start" value="<?= $exam->date_start ?>" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Due Date</span>
                            </div>
                            <label for=""><span>Due Date</span></label>
                            <div class="error-container">
                                <input type="date" name="due_date" placeholder="Due Date" value="<?= $exam->due_date ?>" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Exam File</span>
                            </div>
                            <label for=""><span>Exam File</span></label>
                            <div class="error-container">
                                <input type="file" name="file" placeholder="Exam File" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description (Optional)</span>
                            </div>
                            <label for=""><span>Description (Optional)</span></label>

                            <div class="error-container">
                                <textarea name="description" placeholder="Description" <?= !$is_editable ? "readonly" : "" ?>><?= $exam->description ?></textarea>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                      <?php if($is_editable): ?>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                      <?php endif; ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>