<?php
$days = CasesToCombo(DayTypes::cases());

$count = $_POST['count'];
?>

<div class="form-group-container flex group-item">
    <div class="form-group tooltip">
        <div class="tooltiptext">
            <span>Day</span>
        </div>
        <label for=""><span>Day</span></label>

        <div class="error-container">
            <?= CreateComboBox("day_" . $count, "Day", $days) ?>
        </div>
    </div>
    <div class="form-group tooltip">
        <div class="tooltiptext">
            <span>Start Time</span>
        </div>
        <label for=""><span>Start Time</span></label>
        <div class="error-container">
            <input type="time" name="start_time_<?= $count ?>" placeholder="Start Time" >
        </div>
    </div>
    <div class="form-group tooltip">
        <div class="tooltiptext">
            <span>End Time</span>
        </div>
        <label for=""><span>End Time</span></label>

        <div class="error-container">
            <input type="time" name="end_time_<?= $count ?>" placeholder="End Time" >
        </div>
    </div>
</div>