<?php
global $APPLICATION,$SESSION;

$courseControl = $APPLICATION->FUNCTIONS->COURSE_CONTROL;

$days = CasesToCombo(DayTypes::cases());

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Schedule</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot group-items">
                    <div class="form-group-container flex group-item">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Day</span>
                            </div>
                            <label for=""><span>Day</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("day", "Day", $days) ?>
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Start Time</span>
                            </div>
                            <label for=""><span>Start Time</span></label>
                            <div class="error-container">
                                <input type="time" name="start_time" placeholder="Start Time" >
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>End Time</span>
                            </div>
                            <label for=""><span>End Time</span></label>

                            <div class="error-container">
                                <input type="time" name="end_time" placeholder="End Time" >
                            </div>
                        </div>
                    </div>

                    <div class="added-groups">

                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="text-button add-new-schedule">
                                <div class="text">
                                    <span>NEW SCHEDULE</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>