<div class="main-list-list">
    <a href="/me/profile">
        <li class="item">
            <div class="icon">
                <?= UseIcon('smiley-thin') ?>
            </div>
                <div class="item-content">
                    <div class="left">
                        <div class="text">
                            <span>Your Profile</span>
                        </div>
                    </div>
                </div>
        </li>
    </a>

    <a href="/settings">
        <li class="item">
            <div class="icon">
                <?= UseIcon('gear-thin') ?>
            </div>
            <div class="item-content">
                <div class="left">
                    <div class="text">
                        <span>Settings</span>
                    </div>
                </div>
            </div>
        </li>
    </a>

    <a href="/logout">
    <li class="item">
        <div class="icon">
            <?= UseIcon('arrow-u-up-left-thin') ?>
        </div>
            <div class="item-content">
                <div class="left">
                    <div class="text">
                        <span>Logout</span>
                    </div>
                </div>
            </div>
    </li>
    </a>

</div>