<?php

global $APPLICATION, $USER_HEADER_BODY, $SESSION;

$control = $APPLICATION->FUNCTIONS->USER_CONTROL;
$RECORDS = $control->filterRecords(['user_type' => 2],true);

?>

<?php include "public/views/pages/structures/html_headings.phtml" ?>

<title>Students</title>

<script type="module" src="/public/assets/scripts/libraries/ckeditor.js"></script>
<script type="module" src="/public/assets/scripts/libraries/freewall.js"></script>

<?php include "public/views/pages/structures/html_heading_closing.phtml" ?>

<?php include "public/views/pages/structures/html_body_open.phtml" ?>

<?php include "public/views/pages/structures/html_opening_parent.phtml" ?>

<div class="left-content">

    <?php include "public/views/pages/structures/html_navbar.phtml" ?>

    <?php include "public/views/pages/structures/html_right_heading.phtml" ?>

</div>

<div class="right-content">

    <div class="right-body">
        <div class="main-body-content-parent">
            <div class="main-body-header">
                <div class="header-nav">
                    <div class="left">
                        <div class="title">
                            <h2>Newsfeed</h2>
                        </div>
                    </div>
                    <div class="right"></div>
                </div>
            </div>
            <div class="main-body-body newsfeed-parent">
               <div class="newsfeed-flex">
                   <div class="newsfeed-main-container">

                       <div class="post-creator-container">
                           <div class="creator-head">
                               <div class="photo">
                                   <div class="image">
                                       <img src="<?= $SESSION->getPhotoURL()?>" alt="">
                                   </div>
                               </div>
                               <div class="texts">
                                   <p class="primary">Create a Post</p>
                                   <p class="secondary">What's on your mind, <?= $SESSION->displayName ?>?</p>
                               </div>
                           </div>
                           <div class="creator-body">
                               <div class="textarea-container">
                                   <span>Create a Post</span>
                               </div>
                           </div>
                       </div>


                       <?php for ($i = 0; $i < 5; $i++): ?>
                           <div class="post-container">
                               <div class="post-head">
                                   <div class="photo">
                                       <div class="image"></div>
                                   </div>
                                   <div class="texts">
                                       <p class="primary">Name Primary</p>
                                       <p class="secondary">Description Secondary</p>
                                   </div>
                               </div>
                               <div class="post-body">
                                   <div class="post-content">
                                       Lorem ipsum dolor sit amet, consectetur adipisicing elit. Architecto eos eveniet, fuga fugit illo, incidunt iste itaque laboriosam nam nesciunt nostrum reiciendis vitae voluptate. Amet animi autem commodi, cupiditate deserunt dolorem doloremque dolores earum eligendi explicabo, illo impedit incidunt ipsa magni minus molestiae perspiciatis porro provident quia quibusdam quos reprehenderit saepe sapiente sed, sequi sint tempora voluptatibus. Harum molestiae optio voluptatem! Aperiam architecto assumenda beatae consectetur corporis deserunt distinctio dolore ducimus et harum hic illum ipsam minus odio officiis, pariatur quae quasi quisquam quos recusandae reiciendis, suscipit vero voluptatem. Modi provident quia suscipit veniam vitae! Aut cum deserunt excepturi voluptatum.
                                   </div>
                               </div>
                               <div class="post-footer">
                                   <div class="reaction-container">
                                       <div class="date-content">
                                           <small>Thu, Apr 11, 2024 at 11:55 am</small>
                                       </div>
                                       <div class="reaction-content">
                                           <div class="text-button">
                                               <div class="text">
                                                   <span>Like</span>
                                               </div>
                                           </div>
                                       </div>
                                   </div>
                                   <div class="reaction-content-result">
                                       <span>13 People like this</span>
                                   </div>
                               </div>
                           </div>
                       <?php endfor ?>

                   </div>
                   <div class="newsfeed-announcement">
                       <div class="announcement-title">
                           <h2>Announcements</h2>
                       </div>
                   </div>
               </div>
            </div>
        </div>
    </div>

    <?php include "public/views/pages/structures/html_pipes.phtml" ?>
    <script type="module" src="/public/assets/scripts/pages/superadmin/maintenance/newsfeed.js"></script>

    <?php include "public/views/pages/structures/html_closing_parent.phtml" ?>

    <?php include "public/views/pages/structures/html_body_closing.phtml" ?>
