<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$section_id = $data['section_id'];
$professor_id = $data['professor_id'];

$section = $APPLICATION->FUNCTIONS->SECTION_CONTROL->get($section_id, true);

$subjects = $section->getSubjectForProfessor($professor_id);

$subjects = array_map(function($subject) {
    return [
        "section_subject_id" => $subject->section_subject_id,
        "subject_name" => $subject->subject->subject_name
    ];
}, $subjects);

$subjects = ObjectToCombo("subject_name", "section_subject_id", $subjects);

$passing_types = array_map(function($passing_type) {
    return [
        "value" => $passing_type->name,
        "text" => $passing_type->value
    ];
}, PassingTypes::cases());
?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>New Activity</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Subject</span>
                            </div>
                            <label for=""><span>Subject</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("section_subject_id", "Subject", $subjects) ?>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text" name="title" placeholder="Title" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Passing Types</span>
                            </div>
                            <label for=""><span>Passing Types</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("passing_type", "Passing Types", $passing_types) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description (Optional)</span>
                            </div>
                            <label for=""><span>Description (Optional)</span></label>

                            <div class="error-container">
                                <textarea name="description" placeholder="Description" ></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Due Date (Optional)</span>
                            </div>
                            <label for=""><span>Due Date (Optional)</span></label>
                            <div class="error-container">
                                <input type="date" name="due_date" placeholder="Due Date" >
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>File (Optional)</span>
                            </div>
                            <label for=""><span>File (Optional)</span></label>
                            <div class="error-container">
                                <input type="file" name="file" placeholder="File" >
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>