<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$activity = $APPLICATION->FUNCTIONS->ACTIVITY_CONTROL->get($data['id'], true);

$passing_types = array_map(function($passing_type) {
    return [
        "value" => $passing_type->name,
        "text" => $passing_type->value
    ];
}, PassingTypes::cases());

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>Comply Activity</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            
            <form action="" class="form-control">
                    <div class="popup-bot">

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text" placeholder="Title" value="<?= $activity->title ?>" readonly>
                            </div>
                        </div>
                    </div>

                    <?php if($activity->passing_type == "Link"): ?>
                        <div class="form-group-container flex">
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Link</span>
                                </div>
                                <label for=""><span>Link</span></label>
                                <div class="error-container">
                                    <input type="text" name="link" placeholder="Link" >
                                </div>
                            </div>
                        </div>
                        <?php elseif ($activity->passing_type == "Text"): ?>
                            <div class="form-group-container flex">
                                <div class="form-group tooltip">
                                    <div class="tooltiptext">
                                        <span>Text </span>
                                    </div>
                                    <label for=""><span>Text </span></label>

                                    <div class="error-container">
                                        <textarea name="text" placeholder="Text" ></textarea>
                                    </div>
                                </div>
                            </div>

                        <?php elseif ($activity->passing_type == "File"): ?>
                            <div class="form-group-container flex">
                                <div class="form-group tooltip">
                                    <div class="tooltiptext">
                                        <span>File</span>
                                    </div>
                                    <label for=""><span>File</span></label>
                                    <div class="error-container">
                                        <input type="file" name="file" placeholder="File" >
                                    </div>
                                </div>
                            </div>
                    <?php endif ?>
                </div>
              
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>