<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$activity = $APPLICATION->FUNCTIONS->ACTIVITY_CONTROL->get($data['id'], true);

$section_subject = $APPLICATION->FUNCTIONS->SECTION_SUBJECT_CONTROL->get($activity->section_subject_id, true);

$section_id = $section_subject->section_id;
$professor_id = $section_subject->professor_id;

$section = $APPLICATION->FUNCTIONS->SECTION_CONTROL->get($section_id, true);

$subjects = $section->getSubjectForProfessor($professor_id);

$subjects = array_map(function($subject) {
    return [
        "section_subject_id" => $subject->section_subject_id,
        "subject_name" => $subject->subject->subject_name
    ];
}, $subjects);

$subjects = ObjectToCombo("subject_name", "section_subject_id", $subjects);

$passing_types = array_map(function($passing_type) {
    return [
        "value" => $passing_type->name,
        "text" => $passing_type->value
    ];
}, PassingTypes::cases());

$is_editable = $SESSION->user_type == 2;

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Activity</h1>
                </div>
                <div class="paragraph">
                    <p>Provide Information</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                    <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Subject</span>
                            </div>
                            <label for=""><span>Subject</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("section_subject_id", "Subject", $subjects, false, [
                                    "value" => $activity->section_subject_id,
                                    "text" => $section_subject->subject->subject_name
                                ]) ?>
                            </div>
                        </div>
                    </div>

                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text" name="title" placeholder="Title" value="<?= $activity->title ?>" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Passing Types</span>
                            </div>
                            <label for=""><span>Passing Types</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("passing_type", "Passing Types", $passing_types, false, [
                                    "value" => $activity->passing_type,
                                    "text" => ucwords(str_replace("_", " ", $activity->passing_type))
                                ]) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Description (Optional)</span>
                            </div>
                            <label for=""><span>Description (Optional)</span></label>

                            <div class="error-container">
                                <textarea name="description" placeholder="Description" <?= !$is_editable ? "readonly" : "" ?>><?= $activity->description ?></textarea>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Due Date (Optional)</span>
                            </div>
                            <label for=""><span>Due Date (Optional)</span></label>
                            <div class="error-container">
                                <input type="date" name="due_date" placeholder="Due Date" value="<?= $activity->due_date ?>" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>File (Optional)</span>
                            </div>
                            <label for=""><span>File (Optional)</span></label>
                            <div class="error-container">
                                <input type="file" name="file" placeholder="File" <?= !$is_editable ? "readonly" : "" ?>>
                            </div>
                        </div>
                    </div>
                </div>
              
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <?php if ($is_editable): ?>
                            <div class="form-group filled-green">
                                <input type="submit" value="Save">
                            </div>
                        <?php endif; ?>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>