<?php
global $APPLICATION, $ALL_USER_TYPES,$SESSION;

$data = json_decode($_POST['data'], true);

$complied = $APPLICATION->FUNCTIONS->ACTIVITY_COMPLY_CONTROL->get($data['id'], true);

$activity = $APPLICATION->FUNCTIONS->ACTIVITY_CONTROL->get($complied->activity_id, false);

$passing_types = array_map(function($passing_type) {
    return [
        "value" => $passing_type->name,
        "text" => $passing_type->value
    ];
}, PassingTypes::cases());

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-content">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Complied Activity</h1>
                </div>
                <div class="paragraph">
                    <p>View Complied </p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            
            <form action="" class="form-control">
                    <div class="popup-bot">

                    
                    <?php if($complied->grade_score): ?>
                        <div class="form-group-container flex">
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Grade</span>
                                </div>
                                <label for=""><span>Grade</span></label>
                                <div class="error-container">
                                    <input type="text" placeholder="Grade" value="<?= $complied->grade_score['grade']?>" readonly>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Title</span>
                            </div>
                            <label for=""><span>Title</span></label>
                            <div class="error-container">
                                <input type="text" placeholder="Title" value="<?= $activity['title'] ?>" readonly>
                            </div>
                        </div>
                    </div>

                    <?php if($activity['passing_type'] == "Link"): ?>
                        <div class="form-group-container flex">
                            <div class="form-group tooltip">
                                <div class="tooltiptext">
                                    <span>Link</span>
                                </div>
                                <label for=""><span>Link</span></label>
                                <div class="error-container">
                                    <input type="text" name="link" placeholder="Link" value="<?= $complied->link ?>" readonly>
                                </div>
                            </div>
                        </div>
                        <?php elseif ($activity['passing_type'] == "Text"): ?>
                            <div class="form-group-container flex">
                                <div class="form-group tooltip">
                                    <div class="tooltiptext">
                                        <span>Text </span>
                                    </div>
                                    <label for=""><span>Text </span></label>

                                    <div class="error-container">
                                        <textarea name="text" placeholder="Text" readonly><?= $complied->text ?></textarea>
                                    </div>
                                </div>
                            </div>

                        <?php elseif ($activity['passing_type'] == "File"): ?>
                            <div class="form-group-container flex">
                                <div class="form-group tooltip">
                                    <div class="tooltiptext">
                                        <span>File</span>
                                    </div>
                                    <label for=""><span>File</span></label>
                                    <div class="error-container">
                                        <?php if($complied->file): ?>
                                            <div class="file-info">
                                                <span>Filename: <?= basename($complied->file) ?></span>
                                                <br>
                                                <span>Size: <?= filesize($complied->file) ?> bytes</span>
                                            </div>
                                        <?php else: ?>
                                            <p>No file uploaded</p>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                    <?php endif ?>

                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group right-side">
                        <div class="form-group">
                            <?php if ($complied->grade_score): ?>
                                <div class="link edit-btn" data-category="<?= GradeScoreCategories::ACTIVITY->value ?>" data-comply-id="<?= $complied->comply_id ?>" data-id="<?= $complied->grade_score['grade_score_id'] ?>">
                                    <span>Edit Grade</span>
                                </div>
                            <?php else: ?>
                                <div class="link grade-btn" data-category="<?= GradeScoreCategories::ACTIVITY->value ?>" data-id="<?= $complied->comply_id ?>">
                                    <span>Grade Activity</span>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>