<?php
global $APPLICATION, $STUDENT_IN_SECTION_HEADER_BODY;


$data = json_decode($_POST['data'], true);
$id = $data['id'];

$control = $APPLICATION->FUNCTIONS->SECTION_CONTROL;
$userControl = $APPLICATION->FUNCTIONS->USER_CONTROL;
$courseControl = $APPLICATION->FUNCTIONS->COURSE_CONTROL;
$sectionStudentControl = $APPLICATION->FUNCTIONS->SECTION_STUDENT_CONTROL;

$section = $control->get($id, true);
$students = $sectionStudentControl->filterRecords(['section_id' => $id], true);
$courses = $courseControl->getAllRecords(false);
$courses = ObjectToCombo("course_name", "course_id", $courses);

?>
<div class="main-popup-container">
    <div class="popup-background"></div>
    <div class="popup-content">
        <div class="main-popup-table">
            <div class="popup-top">
                <div class="headline">
                    <h1>View Section</h1>
                </div>
                <div class="paragraph">
                    <p>List of Beneficiaries</p>
                </div>

                <div class="floating-button">
                    <div class="close-popup popup-button">
                        <?= UseIcon('close') ?>
                    </div>
                </div>
            </div>
            <form action="" class="form-control">
                <div class="popup-bot">
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Section Name</span>
                            </div>
                            <label for=""><span>Section Name</span></label>
                            <div class="error-container">
                                <input type="text" name="section_name" placeholder="Section Name" value="<?= $section->section_name ?>">
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Select Professor</span>
                            </div>
                            <div class="error-container">
                                <div class="custom-select-box select-professor">
                                    <div class="main-content">
                                        <input type="text" name="adviser_id" placeholder="Select Professor" readonly  value="<?= $section->adviser_id ?>">

                                        <div class="icon">
                                            <svg width="256px" height="256px" viewBox="0 0 256 256" id="Flat" xmlns="http://www.w3.org/2000/svg">
                                                <path d="M138.82861,130.82861l-80,80a4.00026,4.00026,0,0,1-5.65722-5.65722L130.34326,128,53.17139,50.82861a4.00026,4.00026,0,0,1,5.65722-5.65722l80,80A4.0006,4.0006,0,0,1,138.82861,130.82861Zm80-5.65722-80-80a4.00026,4.00026,0,0,0-5.65722,5.65722L210.34326,128l-77.17187,77.17139a4.00026,4.00026,0,0,0,5.65722,5.65722l80-80A4.0006,4.0006,0,0,0,218.82861,125.17139Z"/>
                                            </svg>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="form-group-container flex">
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Semester</span>
                            </div>
                            <label for=""><span>Semester</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("semester", "Semester", CasesToCombo(Semesters::cases()), false, [
                                        "text" => $section->semester,
                                        "value" => $section->semester
                                ]) ?>
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Year Level</span>
                            </div>
                            <label for=""><span>Year Level</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("year_level", "Year Level", CasesToCombo(YearLevels::cases()), false, [
                                    "text" => $section->year_level,
                                    "value" => $section->year_level
                                ]) ?>
                            </div>
                        </div>
                        <div class="form-group tooltip">
                            <div class="tooltiptext">
                                <span>Main Course</span>
                            </div>
                            <label for=""><span>Main Course</span></label>

                            <div class="error-container">
                                <?= CreateComboBox("course_id", "Main Course", $courses, false , [
                                    "text" => $section->course_id,
                                    "value" => $section->course_id
                                ]) ?>
                            </div>
                        </div>
                    </div>

                    <div class="data-table-content">
                        <div class="main-table-container table-component full">
                            <div class="main-table-header">
                                <div class="table-header">
                                    <div class="left">
                                        <div class="title">
                                            <h2>Students</h2>
                                        </div>
                                    </div>
                                    <div class="center"></div>
                                    <div class="right"></div>
                                </div>
                                <div class="table-buttons">
                                    <div class="left"></div>
                                    <div class="right">
                                        <div class="icon-button table-button show-component" data-name="delete-request">
                                            <div class="icon">
                                                <?= UseIcon("trash-thin") ?>
                                            </div>
                                        </div>
<!---->
<!--                                        <div class="icon-button table-button show-component" data-name="edit-request">-->
<!--                                            <div class="icon">-->
<!--                                                --><?php //= UseIcon("pencil-thin") ?>
<!--                                            </div>-->
<!--                                        </div>-->

                                        <div class="icon-button table-button show-component" data-name="add-request">
                                            <div class="icon">
                                                <?= UseIcon("plus-thin") ?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="main-table-body main-table-requests">
                                <?= CreateTable([
                                    "content" => $STUDENT_IN_SECTION_HEADER_BODY,
                                    "data" => $students,
                                    "id" => "section_student_id"
                                ]) ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="popup-footer">
                    <div class="form-group-container submit-group">
                        <div class="form-group">
                            <div class="link clear-form">
                                <span>Clear</span>
                            </div>
                        </div>
                        <div class="form-group filled-green">
                            <input type="submit" value="Save">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>